### ISSUE TITLE
Labelling Issue

### ISSUE THREAD

**Issue by twutmc** [OrdnanceSurvey/OS-VectorMap-District-stylesheets#2]
We're having issues with the stylesheets in QGIS 2.16 & 2.18. From the attached picture every road segment is labelled although Merge connected lines to avoid duplicate labels is ticked for (Level 0 -  Fill)

![capture](https://cloud.githubusercontent.com/assets/17278016/19851723/4b2a11d6-9f57-11e6-9a0a-4aced8b0347d.JPG)

**Comment by ghost** [comment]
Sorry to hear you're having problems. We have only recently obtained access to the later versions of QGIS so there may be a few issues still to iron out. We will investigate.

**Comment by ghost** [comment]
I believe this to be an issue or a bug with QGIS, I will report it to them.
We don't want to modify our master stylesheets as we believe them to be correct.

If you are working at fixed scale (as it can't be set to ground units to my knowledge), you could try using the 'Suppress labelling of features smaller than' option to reduce the number of road labels. Not ideal as you will lose some important ones but it might be a short-term resolution for you?

**Comment by Chaz6** [comment]
This is still an issue with QGIS 3.6.1, for example centred at 570459,207220 at a scale of 1:15k.

![image](https://user-images.githubusercontent.com/12680/56053818-0b99bb00-5d4d-11e9-8547-3228f76a152b.png)

**Comment by charleyglynn** [comment]
Hi @Chaz6 

Unfortunately the options for labeling lines in QGIS aren't great and don't appear to have changed/been improved since this issue was originally raised. The 'merge connected lines' option doesn't appear to work effectively.

My best recommendation is to remove the background (road shields) and change the placement method to 'curved' and 'on line'. In my experience this seems to do a better job and produce less duplication - it may even offer you more control.

When time allows we will revisit the stylesheets in this repo and attempt to improve them.

Cheers
Charley
